#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

./makeMesh
runApplication $application

cp ../../../etc/AllcleanAllrunAny.foam ${PWD##*/}.foam

#------------------------------------------------------------------------------
