#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Scale & transfer .stl files
printf 'Running surfaceTransformPoints on %s\n' "${PWD}"
mkdir -p constant/triSurface

# Injection
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/injectionXMinus.stl constant/triSurface/injectionXMinus.stl\
	> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/injectionXPlus.stl constant/triSurface/injectionXPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/injectionYMinus.stl constant/triSurface/injectionYMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/injectionYPlus.stl constant/triSurface/injectionYPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/injectionXMinus.stl constant/triSurface/injectionXMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/injectionXPlus.stl constant/triSurface/injectionXPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/injectionYMinus.stl constant/triSurface/injectionYMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/injectionYPlus.stl constant/triSurface/injectionYPlus.stl\
	>> log.surfaceTransformPoints 2>&1

# Inlet
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/inletXMinus.stl constant/triSurface/inletXMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/inletXPlus.stl constant/triSurface/inletXPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/inletYMinus.stl constant/triSurface/inletYMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/inletYPlus.stl constant/triSurface/inletYPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/inletXMinus.stl constant/triSurface/inletXMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/inletXPlus.stl constant/triSurface/inletXPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/inletYMinus.stl constant/triSurface/inletYMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/inletYPlus.stl constant/triSurface/inletYPlus.stl\
	>> log.surfaceTransformPoints 2>&1

# Outlet
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/outlet.stl constant/triSurface/outlet.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/outlet.stl constant/triSurface/outlet.stl\
	>> log.surfaceTransformPoints 2>&1

# Valve
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/valve.stl constant/triSurface/valve.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/valve.stl constant/triSurface/valve.stl\
	>> log.surfaceTransformPoints 2>&1

# Piston
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/piston.stl constant/triSurface/piston.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/piston.stl constant/triSurface/piston.stl\
	>> log.surfaceTransformPoints 2>&1

# Walls
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
	geometry/walls.stl constant/triSurface/walls.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 3.5)'\
	constant/triSurface/walls.stl constant/triSurface/walls.stl\
	>> log.surfaceTransformPoints 2>&1

# Moving valve
surfaceTransformPoints -translate '(0 0 -0.3)'\
	constant/triSurface/valve.stl constant/triSurface/valve.stl\
	>> log.surfaceTransformPoints 2>&1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
m4 < system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
runApplication checkMesh

#------------------------------------------------------------------------------
