#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Delete old results and system files
rm -rf 0/U.orig constant system/fvSolution system/controlDict

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

#------------------------------------------------------------------------------
