#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Copy mesh
mkdir -p constant/ &&\
	cp -r ../../multiCompression/quadPiston/constant/polyMesh constant/polyMesh

# Copy BCs
cp -r ../../multiCompression/quadPiston/0/U.orig 0

# Copy system files & change them to run with potentialFoam
cp -r ../../multiCompression/quadPiston/system/controlDict system
sed -i "s/multiCompression/potentialFoam/g" system/controlDict
cp -r ../../multiCompression/quadPiston/system/fvSolution system
sed -i "s/SIMPLE/potentialFlow/g" system/fvSolution
sed -i "s/rho|U/p|Phi/g" system/fvSolution

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication $application -writePhi -writep 

# Move results to the folder 1/ to check results with .foam file
mkdir -p 1
[ -f 0/U ]   && mv 0/U   1
[ -f 0/p ]   && mv 0/p   1
[ -f 0/phi ] && mv 0/phi 1
[ -f 0/Phi ] && mv 0/Phi 1

#------------------------------------------------------------------------------
