#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

# Копирование файлов сетки
mkdir -p constant/
cp -r ../../multiCompression/quadPiston/mesh/constant/polyMesh constant/polyMesh

# Копирование граничных условий из проекта с модифицированным ядром
mkdir -p 0/
cp -r ../../multiCompression/quadPiston/case/0/p.orig 0
cp -r ../../multiCompression/quadPiston/case/0/U.orig 0

# Копирование файлов system
cp -r ../../multiCompression/quadPiston/case/system/controlDict system
sed -i "s/multiCompression/potentialFoam/g" system/controlDict
cp -r ../../multiCompression/quadPiston/case/system/fvSolution system
sed -i "s/multiCompression/potentialFlow/g" system/fvSolution

# Запуск расчёта
runApplication $application -writePhi -writep 

# Перемещение файлов расчёта в папку 1 для возможности открытия в solved.foam
mkdir -p 1
mv 0/U 1
mv 0/p 1
mv 0/phi 1
mv 0/Phi 1

#------------------------------------------------------------------------------
