#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Simultaneously create ParaView .foam-file & script to rerun the case
printf '''#!/bin/sh
cd ${0%%/*} || exit 1
foamCleanTutorials && foamRunTutorials || cat `ls -rt log.* |tail -1`
''' > ${PWD##*/}.foam && chmod u+x ${PWD##*/}.foam

m4 < ../../resources/blockMesh/cylPiston.m4 > ../../resources/blockMesh/cylPiston
runApplication blockMesh -dict ../../resources/blockMesh/cylPiston

runApplication topoSet -constant -dict ../../resources/topoSet/cylPiston

# Split the mesh to generate the ACMI coupled patches
runApplication createBaffles -overwrite -dict ../../resources/createBaffles/cylPiston

# runApplication checkMesh

#------------------------------------------------------------------------------