#!/bin/sh
#----------------------------------*-sh-*--------------------------------------
#  =========                 |
#  \\      /  F ield         | OpenFOAM: dualFuelEngline addition to OpenFOAM v7
#   \\    /   O peration     | Website:  https://github.com/StasF1/dualFuelEngine
#    \\  /    A nd           | Copyright (C) 2020 Stanislau Stasheuski
#     \\/     M anipulation  |
# -----------------------------------------------------------------------------
# License
#     This file part of dualFuelEngine – OpenFOAM addition.
#
#     dualFuelEngine (like OpenFOAM) is free software: you can redistribute it 
#     and/or modify it under the terms of the GNU General Public License as
#     published by the Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#
#     dualFuelEngine (like OpenFOAM) is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this repository. If not, see <http://www.gnu.org/licenses/>
#
# File
#     AllcleanAllrunAny
#
# Description
#     Script to rerun any OpenFOAM case
#
#------------------------------------------------------------------------------

cd ${0%/*} || exit 1    # Run from this directory

# Clean
# ~~~~~
if [ -f 'Allclean' ]; then
    ./Allclean
else
    # Source tutorial clean functions
    . $WM_PROJECT_DIR/bin/tools/CleanFunctions

    cleanCase
fi

# Run
# ~~~
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ -f 'Allrun' ]; then
    ./Allrun || cat log.$(getApplication)
else
    (runApplication blockMesh && runApplication $(getApplication))\
    || cat log.$(getApplication)
fi

# -----------------------------------------------------------------------------