#!/bin/sh
#----------------------------------*-sh-*--------------------------------------
#  =========                 |
#  \\      /  F ield         | OpenFOAM: dualFuelEngline addition to OpenFOAM v7
#   \\    /   O peration     | Website:  https://github.com/StasF1/dualFuelEngine
#    \\  /    A nd           | Copyright (C) 2020 Stanislau Stasheuski
#     \\/     M anipulation  |
# -----------------------------------------------------------------------------
# License
#     This file part of dualFuelEngine – OpenFOAM addition.
#
#     dualFuelEngine (like OpenFOAM) is free software: you can redistribute it 
#     and/or modify it under the terms of the GNU General Public License as
#     published by the Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#
#     dualFuelEngine (like OpenFOAM) is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this repository. If not, see <http://www.gnu.org/licenses/>
#
# File
#     etc/linksRecreator
#
# Description
#     Script to recreate symbolic links to run tutorials using Ubuntu WSL
#
#------------------------------------------------------------------------------

cd ${0%/*} || exit 1    # Run from this directory

cd ../tutorials/multiCompressionFoam

#- tube
cd tube && printf 'Running linksRecreator on %s\n' "${PWD}"

cd constant # && rm -r *Properties
ln -sf ../../RiemannTube/constant/thermophysicalProperties thermophysicalProperties
ln -sf ../../RiemannTube/constant/transportProperties transportProperties

cd ../system # && rm -r fvSchemes
ln -sf ../../RiemannTube/system/fvSchemes fvSchemes
ln -sf ../../RiemannTube/system/fvSolution fvSolution


#- closedPipe
cd ../../closedPipe && printf 'Running linksRecreator on %s\n' "${PWD}"

cd 0 # && rm -r T alpha*
ln -sf ../../RiemannTube/0/T.orig T
ln -sf ../../RiemannTube/0/alphaAir.orig alphaAir
ln -sf ../../RiemannTube/0/alphaGas.orig alphaGas

cd ../constant # && rm -r *Properties
ln -sf ../../RiemannTube/constant/thermophysicalProperties thermophysicalProperties
ln -sf ../../RiemannTube/constant/transportProperties transportProperties

cd ../system # && rm -r fvSchemes
ln -sf ../../RiemannTube/system/fvSchemes fvSchemes


#- cylPiston
cd ../../cylPiston && printf 'Running linksRecreator on %s\n' "${PWD}"

cd 0 # && rm -r T U alpha* p
ln -sf ../../quadPiston/0/T.orig T
ln -sf ../../quadPiston/0/U.orig U
ln -sf ../../quadPiston/0/alphaAir.orig alphaAir
ln -sf ../../quadPiston/0/alphaGas.orig alphaGas
ln -sf ../../quadPiston/0/p.orig p

cd ../constant # && rm -r *Properties
ln -sf ../../RiemannTube/constant/thermophysicalProperties thermophysicalProperties
ln -sf ../../RiemannTube/constant/transportProperties transportProperties

cd ../system # && rm -r fv* meshQualityDict snappyHexMeshDict surfaceFeaturesDict
ln -sf ../../RiemannTube/system/fvSchemes fvSchemes
ln -sf ../../RiemannTube/system/fvSolution fvSolution
ln -sf ../../quadPiston/system/meshQualityDict meshQualityDict
ln -sf ../../quadPiston/system/snappyHexMeshDict snappyHexMeshDict
ln -sf ../../quadPiston/system/surfaceFeaturesDict surfaceFeaturesDict


#- cylSym2D
cd ../../cylSym2D && printf 'Running linksRecreator on %s\n' "${PWD}"
# rm -r Allclean Allmesh
ln -sf ../../../dyMFoam/cylSym2D/Allclean Allclean
ln -sf ../../../dyMFoam/cylSym2D/Allmesh Allmesh

cd 0 # && rm -r include cellMotionUz pointMotionUz
ln -sf ../../../dyMFoam/cylSym2D/0/include include
ln -sf ../../../dyMFoam/cylSym2D/0/cellMotionUz.orig cellMotionUz
ln -sf ../../../dyMFoam/cylSym2D/0/pointMotionUz.orig pointMotionUz

cd ../constant # && rm -r dynamicMeshDict *Properties
ln -sf ../../../dyMFoam/cylSym2D/constant/dynamicMeshDict dynamicMeshDict
ln -sf ../../RiemannTube/constant/thermophysicalProperties thermophysicalProperties
ln -sf ../../RiemannTube/constant/transportProperties transportProperties

cd ../system # && rm -r fv* blockMeshDict createBafflesDict topoSetDict
ln -sf ../../RiemannTube/system/fvSchemes fvSchemes
ln -sf ../../RiemannTube/system/fvSolution fvSolution
ln -sf ../../../dyMFoam/cylSym2D/system/blockMeshDict blockMeshDict
ln -sf ../../../dyMFoam/cylSym2D/system/createBafflesDict
ln -sf ../../../dyMFoam/cylSym2D/system/topoSetDict


#- quadPiston
cd ../../quadPiston && printf 'Running linksRecreator on %s\n' "${PWD}"

cd constant # && rm -r *Properties
ln -sf ../../RiemannTube/constant/thermophysicalProperties thermophysicalProperties
ln -sf ../../RiemannTube/constant/transportProperties transportProperties

cd ../system # && rm -r fv*
ln -sf ../../RiemannTube/system/fvSchemes fvSchemes
ln -sf ../../RiemannTube/system/fvSolution fvSolution

#------------------------------------------------------------------------------