#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Scale & transfer .stl files
printf 'Running surfaceTransformPoints on %s\n' "${PWD}"
mkdir -p constant/triSurface

# Injection
surfaceTransformPoints -translate '(0 0 3500)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/cylPiston/motionMesh/injection.stl constant/triSurface/injection.stl\
    > log.surfaceTransformPoints 2>&1

# Inlet
surfaceTransformPoints -translate '(0 0 3500)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/cylPiston/motionMesh/inlet.stl constant/triSurface/inlet.stl\
    >> log.surfaceTransformPoints 2>&1

# Piston
surfaceTransformPoints -translate '(0 0 3500)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/cylPiston/motionMesh/piston.stl constant/triSurface/piston.stl\
    >> log.surfaceTransformPoints 2>&1

# Valve
surfaceTransformPoints -translate '(0 0 3500)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/cylPiston/motionMesh/valve.stl constant/triSurface/valve.stl\
    >> log.surfaceTransformPoints 2>&1

# Walls
surfaceTransformPoints -translate '(0 0 3500)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/cylPiston/motionMesh/cylinder.stl constant/triSurface/cylinder.stl\
    >> log.surfaceTransformPoints 2>&1

# Moving valve & piston
surfaceTransformPoints -translate '(0 0 -0.3)'\
    constant/triSurface/valve.stl constant/triSurface/valve.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -translate '(0 0 0.42)'\
    constant/triSurface/piston.stl constant/triSurface/piston.stl\
    >> log.surfaceTransformPoints 2>&1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
m4 < system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
runApplication checkMesh

#------------------------------------------------------------------------------
