#!/bin/sh

# Путь к проекту и открытие его в Finder
cd /Volumes/HDD/OpenFOAM
cd twoFuelEngine/quadPiston # вставить название папки проекта
cd mesh/

# Настройки параметров разбиения сетки
open -a TextMate system/blockMeshDict system/surfaceFeatureExtractDict system/snappyHexMeshDict system/meshQualityDict &

# Открытие скриптов для генерации/регенерации сетки
open -a TextMate firstMesh.sh remesh.sh hardRemesh.sh &


##################################################
osascript -e 'tell application "Terminal" to quit'
