#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

# Копирование .stl файлов в mesh/ для генерации на их основе сетки
cp ../geometry/*.stl constant/triSurface

# Построение сетки
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication $application -overwrite

# Анализ сетки
runApplication checkMesh

#------------------------------------------------------------------------------
