#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

cp ../../../etc/AllcleanAllrunAny.foam ${PWD##*/}.foam

runApplication blockMesh

runApplication $application
# runApplication decomposePar -force
# runParallel $application
# runApplication reconstructPar


#------------------------------------------------------------------------------
