#!/bin/sh
#----------------------------------*-sh-*--------------------------------------
# =========					|
# \\	  /	 F ield			| OpenFOAM: Addition to OpenFOAM v6
#  \\	 /	 O peration		| Website:	https://github.com/StasF1/dualFuelEngine
#   \\	/	 A nd			| Copyright (C) 2019 Stanislau Stasheuski
#    \\/	 M anipulation	|
#------------------------------------------------------------------------------
# License
#     This file is not part of OpenFOAM, but part of dualFuelEngine – OpenFOAM
#     addition.
#   
#     dualFuelEngine (like OpenFOAM) is free software: you can redistribute it 
#     and/or modify it under the terms of the GNU General Public License as
#     published by the Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#   
#     dualFuelEngine (like OpenFOAM) is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU General Public License for more details.
#   
#     You should have received a copy of the GNU General Public License
#     along with this repository. If not, see <http://www.gnu.org/licenses/>
#
# File
#     etc/v5x-compile
#
# Description
#     Script to make dualFuelEngine compiled using OpenFOAM v5
#
#------------------------------------------------------------------------------

cd ${0%/*} || exit 1 # Run from this directory

# Corrections in the solvers/
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
#- Correct multiCompression.C
sed -i "s/setRootCaseLists.H/setRootCase.H/g"\
	../solvers/multiCompression/multiCompression.C
sed -i "s/simple.loop(runTime)/simple.loop()/g"\
	../solvers/multiCompression/multiCompression.C

#- Correct multiCompressionDyM.C
sed -i "s/setRootCaseLists.H/setRootCase.H/g"\
	../solvers/multiCompression/multiCompressionDyM/multiCompressionDyM.C
sed -i "s/simple.loop(runTime)/simple.loop()/g"\
	../solvers/multiCompression/multiCompressionDyM/multiCompressionDyM.C


# Corrections in the tutorials/multiCompression/
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#- Remove .orig extenstions
for i in ../tutorials/multiCompression/cylPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/multiCompression/quadPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/multiCompression/RiemannTube/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/multiCompression/tube/0/*.orig; do mv -i "$i" "${i%.orig}"; done

#- Correct quadPiston case
sed -i "s/surfaceFeatures/surfaceFeatureExtract/g"\
	../tutorials/multiCompression/quadPiston/makeMesh
mv ../tutorials/multiCompression/quadPiston/system/surfaceFeaturesDict\
	../tutorials/multiCompression/quadPiston/system/surfaceFeatureExtractDict
sed -i "s+mesh/generation/meshQualityDict.cfg+meshQualityDict+g"\
	../tutorials/multiCompression/quadPiston/system/meshQualityDict

#- Correct cylPiston case
sed -i "s/surfaceFeatures/surfaceFeatureExtract/g"\
	../tutorials/multiCompression/cylPiston/makeMesh
mv ../tutorials/multiCompression/cylPiston/system/surfaceFeaturesDict\
	../tutorials/multiCompression/cylPiston/system/surfaceFeatureExtractDict
sed -i "s+mesh/generation/meshQualityDict.cfg+meshQualityDict+g"\
	../tutorials/multiCompression/cylPiston/system/meshQualityDict


# Corrections in the tutorials/multiCompressionDyM
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#- Remove .orig extenstions
for i in ../tutorials/multiCompressionDyM/movingWallTube/0/*.orig; do mv -i "$i" "${i%.orig}"; done


# Corrections in other folders (in the tutorials/)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
for i in ../tutorials/potentialFoam/prism/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/potentialFoam/quadPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done

for i in ../tutorials/scalarTransportFoam/prism/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/scalarTransportFoam/quadPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done

#------------------------------------------------------------------------------
