#!/bin/sh
#----------------------------------*-sh-*--------------------------------------
#  =========                 |
#  \\      /  F ield         | OpenFOAM: Addition to OpenFOAM v6
#   \\    /   O peration     | Website:  https://github.com/StasF1/dualFuelEngine
#    \\  /    A nd           | Copyright (C) 2018-2020 Stanislau Stasheuski
#     \\/     M anipulation  |
# ----------------------------------------------------------------------------
# License
#     This file is not part of OpenFOAM, but part of dualFuelEngine – OpenFOAM
#     addition.
#   
#     dualFuelEngine (like OpenFOAM) is free software: you can redistribute it 
#     and/or modify it under the terms of the GNU General Public License as
#     published by the Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#   
#     dualFuelEngine (like OpenFOAM) is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU General Public License for more details.
#   
#     You should have received a copy of the GNU General Public License
#     along with this repository. If not, see <http://www.gnu.org/licenses/>
#
# File
#     etc/v5x-compile
#
# Description
#     Script to make dualFuelEngine compiled using OpenFOAM v5
#
#------------------------------------------------------------------------------

cd ${0%/*} || exit 1 # Run from this directory

# Corrections in the solvers/
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
#- Correct multiCompressionFoam.C
sed -i "s/setRootCaseLists.H/setRootCase.H/g"\
    ../solvers/multiCompressionFoam/multiCompressionFoam.C
sed -i "s/simple.loop(runTime)/simple.loop()/g"\
    ../solvers/multiCompressionFoam/multiCompressionFoam.C

#- Correct multiCompressionFoamDyM.C
sed -i "s/setRootCaseLists.H/setRootCase.H/g"\
    ../solvers/multiCompressionFoam/multiCompressionFoamDyM/multiCompressionFoamDyM.C
sed -i "s/simple.loop(runTime)/simple.loop()/g"\
    ../solvers/multiCompressionFoam/multiCompressionFoamDyM/multiCompressionFoamDyM.C


# Corrections in the tutorials/multiCompressionFoam/
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#- Remove .orig extenstions
for i in ../tutorials/multiCompressionFoam/cylPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/multiCompressionFoam/quadPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/multiCompressionFoam/RiemannTube/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/multiCompressionFoam/tube/0/*.orig; do mv -i "$i" "${i%.orig}"; done

#- Correct quadPiston case
sed -i "s/surfaceFeatures/surfaceFeatureExtract/g"\
    ../tutorials/multiCompressionFoam/quadPiston/makeMesh
mv ../tutorials/multiCompressionFoam/quadPiston/system/surfaceFeaturesDict\
    ../tutorials/multiCompressionFoam/quadPiston/system/surfaceFeatureExtractDict
sed -i "s+mesh/generation/meshQualityDict.cfg+meshQualityDict+g"\
    ../tutorials/multiCompressionFoam/quadPiston/system/meshQualityDict

#- Correct cylPiston case
sed -i "s/surfaceFeatures/surfaceFeatureExtract/g"\
    ../tutorials/multiCompressionFoam/cylPiston/makeMesh
mv ../tutorials/multiCompressionFoam/cylPiston/system/surfaceFeaturesDict\
    ../tutorials/multiCompressionFoam/cylPiston/system/surfaceFeatureExtractDict
sed -i "s+mesh/generation/meshQualityDict.cfg+meshQualityDict+g"\
    ../tutorials/multiCompressionFoam/cylPiston/system/meshQualityDict


# Corrections in the tutorials/multiCompressionFoamDyM
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#- Remove .orig extenstions
for i in ../tutorials/multiCompressionFoamDyM/movingWallTube/0/*.orig; do mv -i "$i" "${i%.orig}"; done


# Corrections in other folders (in the tutorials/)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
for i in ../tutorials/potentialFoam/prism/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/potentialFoam/quadPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done

for i in ../tutorials/scalarTransportFoam/prism/0/*.orig; do mv -i "$i" "${i%.orig}"; done
for i in ../tutorials/scalarTransportFoam/quadPiston/0/*.orig; do mv -i "$i" "${i%.orig}"; done

#------------------------------------------------------------------------------
