#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Копирование файлов сетки и постоянных
mkdir -p constant
cp -r ../case/constant/transportProperties constant
cp -r ../mesh/constant/polyMesh constant/polyMesh

# Копирование граничных условий из проекта с модифицированным ядром
mkdir -p 0
cp -r ../case/0/T.orig 0
cp -r ../case/1/U 0

# Копирование файлов system из проекта с модифицированным ядром
cp -r ../case/system/controlDict system
cp -r ../case/system/fvSolution system
cp -r ../case/system/fvSchemes system
sed -i "s/multiCompression/scalarTransportFoam/g" system/controlDict
cp -r ../case/system/fvSolution system
sed -i "s/multiCompression/SIMPLE/g" system/fvSolution

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

# Запуск расчёта
runApplication $application

#------------------------------------------------------------------------------
