#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# dyMFoam
# ~~~~~~~
#- dynamicInkJetFvMesh solver
dyMFoam/dynamicInkJetFvMesh/tube/./Allclean
dyMFoam/dynamicInkJetFvMesh/quadPiston/./Allclean
dyMFoam/dynamicInkJetFvMesh/cylPiston/./Allclean


# multiCompression
# ~~~~~~~~~~~~~~~~
multiCompression/RiemannTube/./Allclean
multiCompression/tube/./Allclean
multiCompression/quadPiston/./Allclean
multiCompression/cylPiston/./Allclean

#------------------------------------------------------------------------------
