#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# multiCompression
multiCompression/RiemannTube/./Allclean
multiCompression/tube/./Allclean
multiCompression/quadPiston/./Allclean
multiCompression/cylPiston/./Allclean

#------------------------------------------------------------------------------
