#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

for CASE_PATH in multiCompressionFoam/*; do
    if test -f "$CASE_PATH/post_process.py"; then
        $CASE_PATH/./post_process.py
    fi
done