#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

# Копирование файлов сетки
cp -r ../mesh/constant/polyMesh constant

# Запуск расчёта
runApplication $application -writep | tee -a case.log

# Перемещение файлов расчёта в папку 1 для возможности открытия в solved.foam
mkdir -p 1
mv 0/U 1
mv 0/p 1
# mv 0/T 1
# mv 0/phi 1
# mv 0/Phi 1
# mv 0/div\(phi\) 1

#------------------------------------------------------------------------------
