#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp ../../../../etc/scripts/AllcleanAllrunAny ${PWD##*/}.foam

runApplication blockMesh -dict ../../../resources/blockMesh/shockTube
runApplication setFields
runApplication $(getApplication)
# runApplication -s sample  postProcess -func sample

#------------------------------------------------------------------------------
