#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
runApplication $application -writePhi -writep

mkdir -p 1
mv 0/U 1
mv 0/p 1
mv 0/phi 1
mv 0/Phi 1

#------------------------------------------------------------------------------
