#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Scale .stl
printf 'Running surfaceTransformPoints on %s\n' "${PWD}"
mkdir -p constant/triSurface

# Injection
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/injection.stl constant/triSurface/injectionXMinus.stl\
    > log.surfaceTransformPoints 2>&1
surfaceTransformPoints -rollPitchYaw '(0 0 90)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/injection.stl constant/triSurface/injectionXPlus.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -rollPitchYaw '(0 0 270)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/injection.stl constant/triSurface/injectionYMinus.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -rollPitchYaw '(0 0 180)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/injection.stl constant/triSurface/injectionYPlus.stl\
    >> log.surfaceTransformPoints 2>&1

# Inlet
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/inlet.stl constant/triSurface/inletXMinus.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -rollPitchYaw '(0 0 90)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/inlet.stl constant/triSurface/inletXPlus.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -rollPitchYaw '(0 0 270)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/inlet.stl constant/triSurface/inletYMinus.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -rollPitchYaw '(0 0 180)' -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/inlet.stl constant/triSurface/inletYPlus.stl\
    >> log.surfaceTransformPoints 2>&1

# Other
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/outlet.stl constant/triSurface/outlet.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/valve.stl constant/triSurface/valve.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/piston.stl constant/triSurface/piston.stl\
    >> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)'\
    ../../resources/geometry/quadPiston/walls.stl constant/triSurface/walls.stl\
    >> log.surfaceTransformPoints 2>&1

# Moving valve
surfaceTransformPoints -translate '(0 0 -0.25)'\
    constant/triSurface/valve.stl constant/triSurface/valve.stl\
    >> log.surfaceTransformPoints 2>&1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
runApplication checkMesh

#------------------------------------------------------------------------------