#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp ../../../etc/AllcleanAllrunAny.foam ${PWD##*/}.foam

runApplication blockMesh

runApplication topoSet -constant

# Split the mesh to generate the ACMI coupled patches
runApplication createBaffles -overwrite

#------------------------------------------------------------------------------