#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp ../../../etc/scripts/AllcleanAllrunAny ${PWD##*/}.foam

m4 < system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh

runApplication topoSet -constant

# Split the mesh to generate the ACMI coupled patches
runApplication createBaffles -overwrite

runApplication checkMesh

#------------------------------------------------------------------------------