#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# Удаление cтарых результатов расчёта
rm -rf 0
rm -rf constant
rm -rf system

#------------------------------------------------------------------------------
