#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Copy BCs
mkdir -p 0
cp -r ../../multiCompression/quadPiston/0/T.orig 0
cp -r ../../potentialFoam/quadPiston/1/U 0

# Copy mesh
cp -r ../../multiCompression/quadPiston/constant/polyMesh constant/polyMesh

# Copy system files & change them to run with scalarTransportFoam
mkdir -p system
cp -r ../../multiCompression/quadPiston/system/controlDict system
cp -r ../../multiCompression/quadPiston/system/fvSolution system
cp -r ../../multiCompression/quadPiston/system/fvSchemes system
sed -i "s/multiCompression/scalarTransportFoam/g" system/controlDict

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication $application

#------------------------------------------------------------------------------
