#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Scale .stl
printf 'Running surfaceTransformPoints on %s\n' "${PWD}"
mkdir -p constant/triSurface

# Injection
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/injectionXMinus.stl constant/triSurface/injectionXMinus.stl\
	> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/injectionXPlus.stl constant/triSurface/injectionXPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/injectionYMinus.stl constant/triSurface/injectionYMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/injectionYPlus.stl constant/triSurface/injectionYPlus.stl\
	>> log.surfaceTransformPoints 2>&1

# Inlet
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/inletXMinus.stl constant/triSurface/inletXMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/inletXPlus.stl constant/triSurface/inletXPlus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/inletYMinus.stl constant/triSurface/inletYMinus.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/inletYPlus.stl constant/triSurface/inletYPlus.stl\
	>> log.surfaceTransformPoints 2>&1

# Other
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/outlet.stl constant/triSurface/outlet.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/valve.stl constant/triSurface/valve.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/piston.stl constant/triSurface/piston.stl\
	>> log.surfaceTransformPoints 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' -rollPitchYaw '(0 90 0)'\
	geometry/walls.stl constant/triSurface/walls.stl\
	>> log.surfaceTransformPoints 2>&1

# Moving valve
surfaceTransformPoints -translate '(-0.25 0 0)'\
	constant/triSurface/valve.stl constant/triSurface/valve.stl\
	>> log.surfaceTransformPoints 2>&1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
runApplication checkMesh

#------------------------------------------------------------------------------