#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

./Allmesh
runApplication setFields -dict ../cylPiston_multiCompressionFoam/system/setFieldsDict

#- Run serial
runApplication $application

#- Run parallel
# runApplication decomposePar
# runParallel $application
# runApplication reconstructPar

#------------------------------------------------------------------------------