#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp ../../../../etc/scripts/AllcleanAllrunAny ${PWD##*/}.foam

m4 < ../../../resources/blockMesh/cylCyclic2D.m4 > ../../../resources/blockMesh/cylCyclic2D
runApplication blockMesh -dict ../../../resources/blockMesh/cylCyclic2D

runApplication topoSet -constant -dict ../../../resources/topoSet/cylPiston

# Split the mesh to generate the ACMI coupled patches
runApplication createBaffles -overwrite -dict ../../../resources/createBaffles/cylPiston

runApplication checkMesh

#------------------------------------------------------------------------------