#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh
runApplication setFields -dict ../cylCyclic2D_multiCompressionFoam/system/setFieldsDict

#- Run serial
runApplication $(getApplication)

#- Run parallel
# runApplication decomposePar -force -dict ../cylCyclic2D_multiCompressionFoam/system/decomposeParDict
# runParallel $(getApplication)
# runApplication reconstructPar

# -----------------------------------------------------------------------------