#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp ../../../etc/scripts/AllcleanAllrunAny ${PWD##*/}.foam

./Allmesh

#- Run serial
# runApplication $(getApplication)

#- Run parallel
runApplication decomposePar -force
runParallel $(getApplication)
runApplication reconstructPar

#------------------------------------------------------------------------------